export default () => ({
  isLoadingCollectionList: false,
  collectionsList: [],
  assignedCollections: [],
  isLoadingAssignedCollections: false,
  collectionTypes: [],
  isLoadingCollectionTypes: false,
  collectionsOwedByStudent: [],
  isLoadingCollectionsOwedByStudent: true,
  collectionsByStudent: [],
  isLoadingCollectionsByStudent: false,
  collectionStatuses: [],
  studentBalance: {},
  isLoadingCollection: false,
  collections: { data: [], total: 0 },
  chargesFrequency: [],
});
